name: Render site

on:
  schedule:
  - cron: "*/60 * * * *"
  push:
    branches: [ main ]
    
jobs:
  build:
    name: render dashboard site
    runs-on: ubuntu-18.04 
    container: 
     image: myominnoo/dashboard:malcon0.3
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with: 
          ref: 'main'
      - name: Render scripts and build site
        run: |
            bash ./scripts/data_refresh.sh "main" "$PAT_KEY"
        env:     
          PAT_KEY: ${{ secrets.PAT_KEY }} 
