name: Data Refresh

on:
  push:
    branches: [ main ]
jobs:
  build:
    name: refresh the dashboard
    runs-on: ubuntu-18.04 
    container: 
     image: myominnoo/tidyverse:dev0.1
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with: 
          ref: 'main'
      - name: Data refresh
        run: |
            bash ./scripts/data_refresh.sh "main" "$API_KEY" 
        env:     
          API_KEY: ${{ secrets.PAT_KEY }}
          
# PAT: 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