name: Data Refresh

on: 
  schedule:  
    - cron:  '0 */1 * * *'
jobs:
  build:
    name: refresh the dashboard
    runs-on: ubuntu-18.04 
    container: 
     image: rkrispin/us_electricity:dev.0.0.0.9000
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
        with: 
          ref: 'main'
      - name: Data refresh
        run: |
            bash ./scripts/data_refresh.sh "main" "$API_KEY" 
        env:     
          API_KEY: ${{ secrets.PAT_KEY }}
          
# PAT: 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